apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: proxy
      annotations:
        repository: https://github.com/kublr/keycloak-proxy
    spec:
      containers:
      - name: proxy
        image: quay.io/gambol99/keycloak-proxy:latest
        imagePullPolicy: Always
        args:
          - --config=/etc/secrets/config.yml
          - --discovery-url=https://sso.example.com/auth/realms/hod-test
          - --client-id=broker
          - --client-secret=secret
          - --listen=127.0.0.1:3000
          - --enable-logging=true
          - --enable-json-logging=true
          - --upstream-url=http://127.0.0.1:8080
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
      volumes:
      - name: secrets
        secret:
          secretName: config
